### PR TITLE
Feature spr1 2547 remove uris

### PR DESCRIPTION
**Pull request by ZanelleKM**
## References
_Add references/links to any related issues or PRs. These may include:_
* Fixes #SPR1-2547

## Description
Remove unused features on Collections and collections

List of changes in this PR:
* Removed settings
* Removed white error icons
* Removed permanent uris
* Removed item icons 

- [ ] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & specs/tests), or I have provided reasons as to why that's not possible.
- [ ] My PR passes [TSLint](https://palantir.github.io/tslint/) validation using `yarn run lint`
- [ ] My PR doesn't introduce circular dependencies
- [ ] My PR includes [TypeDoc](https://typedoc.org/) comments for _all new (or modified) public methods and classes_. It also includes TypeDoc for large or complex private methods.
- [ ] My PR passes all specs/tests and includes new/updated specs or tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [ ] If my PR includes new, third-party dependencies (in `package.json`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.

### CODE REVIEW

**Comment by ctgschollar** [comment]
@ZanelleKM you need to work on making more complete commit messages

**Review by ctgschollar — CHANGES_REQUESTED** [review]
Looks pretty good to me. Although your last commit message seems to be unrelated to the change you made. It is the same commit message as you have on another branch, so I think you made a mistake. Please open the branch on your local machine, remove the last commit and commit it again with the correct message. Including the ticket number in your commit message. Once you have the right message you can git push --force.

You should be able to use interactive rebase to change the commit message.

Here is a video on udemy to look at to help you https://sarao.udemy.com/course/git-and-github-bootcamp/learn/lecture/24869826#overview

**Comment by ZanelleKM** [comment]
I managed to revert but not sure why the commit message is not updated @ctgschollar

**Comment by ctgschollar** [comment]
You need to use reset instead of revert. Reset removes commits, whereas revert will go back, but create a new commit.

```
git reset 0010280
git add .
git commit -m "Proper commit message"
git push --force
```
Make sure you only push force when you are sure that the state of the local branch is correct, as you will overwrite what is on github.

**Pull request merged**
